-- Xóa ràng buộc khóa ngoại cũ
ALTER TABLE CTHoaDon
DROP CONSTRAINT FK_CTHoaDon_HoaDon;

ALTER TABLE CTHoaDon
DROP CONSTRAINT FK_CTHoaDon_SanPham;

-- Thêm lại với `ON DELETE CASCADE`
ALTER TABLE CTHoaDon
ADD CONSTRAINT FK_CTHoaDon_HoaDon
FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
ON DELETE CASCADE;

ALTER TABLE CTHoaDon
ADD CONSTRAINT FK_CTHoaDon_SanPham
FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
ON DELETE CASCADE;
