CREATE DATABASE QL_NHAHANG
GO
USE QL_NHAHANG
GO
CREATE TABLE KhachHang(
	MaKhachHang INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	HoTen NVARCHAR(100) NOT NULL,
	SDT_KH NVARCHAR(15) UNIQUE NOT NULL,
	LoaiKH NVARCHAR(20) NOT NULL, /* CÓ THỂ LÀ KHÁCH VÃN LAI , KHÁCH KHÁCH SẠN, KHÁCH VIP */
	NgaySuDung DATETIME NOT NULL,
	TiLeGiamGia DECIMAL(5,2) DEFAULT 0.00,
);
CREATE TABLE NhanVien(
	MaNV INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	HoTen NVARCHAR(100) NOT NULL,
	ChucVu NVARCHAR(20) NOT NULL CHECK (ChucVu IN ('Nhân viên', 'Quản lý')), /* CÓ THỂ LÀ QUẢN LÝ , nhân viên */
	SDT_NV VARCHAR(15) NOT NULL UNIQUE,
	Email_NV NVARCHAR(100) UNIQUE,
	NgayTao  DATETIME DEFAULT GETDATE(),
);

CREATE TABLE DangNhap(
	MaDangNhap INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
	MatKhau VARCHAR(50) NOT NULL,
	MaNV INT not null,
	NgayTao DATETIME DEFAULT GETDATE(),
	TrangThai NVARCHAR(20) NOT NULL CHECK(TrangThai IN('Hoạt động','Khóa')),
	FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
);
CREATE TABLE DanhMucSanPham(
	MaDanhMuc INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TenDanhMuc NVARCHAR(100) NOT Null,
	Loai NVARCHAR(20) NOT NULL Check(Loai In('Đồ uống','Món ăn')),
	MoTa NVARCHAR(200) NULL,
);
CREATE TABLE NhaCungCap(
	MaNhaCungCap INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TenNhaCungCap NVARCHAR(200) NOT NULL,
	SoDienThoai VARCHAR(20) NOT NULL UNIQUE,
	Email NvarChar(100) Null,
);
CREATE TABLE SANPHAM(
	MaSanPham INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TenSanPham NVARCHAR(50) NOT NULL,
	MaDanhMuc INT, -- mối quan hệ n-1 mới bảng danh mục sp
	MaNhaCungCap INT, -- Mối quan hệ n-1 với bảng nhà cung cấp
	Gia DECIMAL(10,2) NOT NULL,
	ThueVAT AS(
		CASE
			WHEN MaDanhMuc = (SELECT MaDanhMuc FROM DanhMucSanPham WHERE TenDanhMuc ='Đồ uống có cồn')
			 Then 10.00
			 ELSE 8.00
			 END
			 ),
	MoTa NVARCHAR(200) NULL,
	SoLuongTonKho INT NOT NULL DEFAULT 0,
	FOREIGN KEY (MaDanhMuc) REFERENCES DanhMucSanPham(MaDanhMuc),
	FOREIGN KEY (MaNhaCungCap) REFERENCES NhaCungCap(MaNhaCungCap),
);